site_name: GERD
site_url: https://caretech-owl.github.io/gerd
repo_url: https://github.com/caretech-owl/gerd
copyright: "&copy; 2025 CareTech OWL"

theme:
  name: material
  features:
    - content.code.copy
    - content.code.annotate
    - navigation.instant
    - navigation.instant.progress
    - navigation.footer
    - header.autohide
    - toc.follow
    - toc.integrate
extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/solid/building-columns
      link: https://caretech-owl.de
markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.inlinehilite
nav:
  - "README.md"
  - "concepts.md"
  - "develop.md"
  - "Api Documentation":
    - "reference/config.md"

plugins:
  - mkdocstrings:
      default_hander: python
      handlers:
        python:
          options:
            inherited_members: true
            members_order: source
            separate_signature: true
            unwrap_annotated: true
            merge_init_into_class: true
            # docstring_section_style: spacy
            signature_crossrefs: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true