name: gerd-environment
dependencies:
  - python=3.12
  - pip
  - pip:
    - transformers
    - faiss-cpu
    - sentence-transformers
    - pydantic
    - pydantic-settings
    - langchain-community
    - jinja2
    - llama-cpp-python
    - orjson