model:
  name: "TheBloke/em_german_leo_mistral-GGUF"
  file: "em_german_leo_mistral.Q5_K_M.gguf"
  temperature: 0.05
  top_k: 50
  top_p: 0.95
  max_new_tokens: 512
  stop: ["<|im_end|>"]
  repetition_penalty: 1.1
  context_length: 2048
  prompt_config:
    text: "Du bist ein hilfreicher Assistent und beantwortest alle Fragen zuverl채ssig und wahrheitsgetreu. USER: {prompt} ASSISTANT:"
features:
  prompt_chaining:
    prompts:
      - text: "{question}"
      - text: "Hier ist eine Aussage:\n{response_1}\n\nErstelle eine Auflistung von Annahmen, um zu dieser Aussage zu gelangen."
      - text: "Hier ist eine Liste von Annahmen:\n{response_2}\n\nF체r jede Annahme stelle fest, ob die Annahme wahr oder falsch ist und erkl채re warum."
      - text: "In Anbetracht der folgenden Fakten:\n{response_3}\n\nWie w체rdest du die folgende Frage beantworten: {question}."
