model:
  name: "Qwen/Qwen2.5-0.5B-Instruct"
  temperature: 0.05
  max_new_tokens: 512
  context_length: 2048
  prompt_setup:
    - ["system", text: "You are a helpful assistant. Please answer the following question in a truthful and brief manner."]
features:
  prompt_chaining:
    prompts:
      - text: "{question}"
      - text: "Here is a statement:\n{response_1}\n\nMake a bullet point list of the assumptions you made when producing the above statement.\n\n"
      - text: "Here is a bullet point list of assertions:\n{response_2}\n\nFor each assertion, determine whether it is true or false. If it is false, explain why.\n\n"
      - text: "{response_3}\n\nIn light of the above facts, how would you answer the question '{question}'"
