model:
  name: "meta-llama/Llama-3.2-1B-Instruct"
  temperature: 0.01
  top_k: 100
  top_p: 0.95
  max_new_tokens: 512
  repetition_penalty: 1.1
  context_length: 2048
output_dir: "lora/lora_instruct"
pad_token_id: 0
modules:
  default: True
