name: gerd-environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip
  - requests
  - pytorch
  - torchvision
  - torchaudio
  - transformers
  - llama-cpp-python
  - sentence-transformers
  - pydantic
  - langchain-community
  - jinja2
  - pip
  - orjson
  - pydantic-settings
  - faiss-cpu
