name: gerd-environment
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - pip
  - pytorch
  - pip:
    - faiss-cpu
    - jinja2
    - langchain-community
    - llama-cpp-python
    - orjson
    - pydantic
    - pydantic-settings
    - requests
    - sentence-transformers
    - transformers
